version: '3'
services:
  blockchain:
    container_name: blockchain
    build: ./blockchain/
    image: blockchain
    networks:
      - wpsite
    volumes:
      - ./blockchain:/app
    ports:
      - "8545:8545"
    restart: always
  frontend:
    container_name: frontend
    build: ./frontend/
    image: frontend
    depends_on:
      - blockchain
    volumes:
      - ./frontend:/app
    networks:
      - wpsite
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    init: true

networks:
  wpsite:
    driver: bridge